spring.application.name=roadworks-report
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/roadworks
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.static-token=roadworks-static-token
